/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        "inter-thin": ["Inter_100Thin"],
        "inter-black": ["Inter_900Black"],
        "inter-regular": ["Inter_400Regular"],
        "inter-medium": ["Inter_500Medium"],
        "inter-bold": ["Inter_700Bold"],
        "inter-semi-bold": ["Inter_600SemiBold"],
        "crimson-regular": ["CrimsonPro_400Regular_Italic"],
      },
      colors: {
        background: "var(--background)",
        text: "black",
        "dark-text": "#121217",
        primary: "#8B85F4",
        // background: "#ffff",
        slate: "#5D5DC9",
        white: "white",
        black: "rgba(255, 255, 255, 0.1)",
        "place-holder": "#A9A9BC",
        "gray-hover": "#EBEBEF",
        gray_hover: "#EBEBEF",
        secondary: "#6C6C89",
        neutral: "rgba(18, 18, 23, 0.02)",
        gray: "rgba(255, 255, 255, 0.10)",
        subtle_surface: "#FFFFFF1A",
        surface_overlay: "#ffff",
        tint: "#0a7ea4",
        "white-text": "#ffff",
        "dark-secondary": "#FFFFFF80",
        // "dark-background": "#141414",
        "dark-background": "#141414",
        "dark-gray-hover": "#FFFFFF33",
        "dark-place-holder": "#FFFFFF33",
        "accent-gray": "#D1D1DB",
        "accent-gray-bolder": "#F7F7F8",
        destructive: "#F53D6B",
        disabled: "#5D5DC9",
        yellow: "#F2C71C",
        olive: "#61500B",
        olive2: "#917711",
        red: "#F53D6B",
        orange: "#FF7D52",
        green: "#39C65D",
        success: "#227738",
        teal: "#20BA90",
      },
      borderRadius: {
        lg: "16px",
      },
      borderWidth: {
        1: 1,
      },
    },
  },
  plugins: [],
};
