import React, { FunctionComponent, useEffect, useRef, useState } from "react";
import { Keyboard, StatusBar, View, useColorScheme } from "react-native";
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from "react-native-reanimated";

import OTPInput from "@/components/inputs/OTPInput";
import BackdropBlur from "@/components/modals/BackdropBlur";
import BaseModal from "@/components/modals/BaseModal";
import QRCodeIcon from "@/components/svgs/qr-code";
import QRCodeIconWhite from "@/components/svgs/qr-code-white";
import { useAppDimensions } from "@/hooks/useAppDimensions";
import { useThemeColors } from "@/hooks/useThemeColor";
import { X } from "lucide-react-native";
import { KeyboardAwareScrollView } from "react-native-keyboard-aware-scroll-view";
import { ResponsiveUi } from "../../ResponsiveUi";

interface Props {
  isVisible: boolean;
  onClose: () => void;
}

const QRCodeAuthModal: FunctionComponent<Props> = ({ isVisible, onClose }) => {
  const colors = useThemeColors();
  const theme = useColorScheme();
  const [otp, setOtp] = useState<string>("");
  const containerRef = useRef<KeyboardAwareScrollView>(null);
  const { wp, hp, isLargeScreen } = useAppDimensions();

  const bottomAnim = useSharedValue(10);

  useEffect(() => {
    const showSubscription = Keyboard.addListener("keyboardDidShow", () => {
      StatusBar.setHidden(true);
      bottomAnim.value = withTiming(hp(35), { duration: 300 });
    });
    const hideSubscription = Keyboard.addListener("keyboardDidHide", () => {
      StatusBar.setHidden(false);
      bottomAnim.value = withTiming(10, { duration: 300 });
    });

    return () => {
      showSubscription.remove();
      hideSubscription.remove();
    };
  }, []);

  const animatedStyle = useAnimatedStyle(() => ({
    bottom: bottomAnim.value,
  }));

  return (
    <KeyboardAwareScrollView
      keyboardShouldPersistTaps="handled"
      ref={containerRef}
      bounces={false}
      showsVerticalScrollIndicator={false}
      contentContainerStyle={{
        paddingBottom: wp(3),
        flexGrow: 1,
        paddingHorizontal: 16,
        paddingTop: 14,
        zIndex: 20,
      }}
    >
      <BaseModal onClose={onClose} isVisible={isVisible}>
        <BackdropBlur onClose={onClose} />
        <Animated.View
          style={[
            {
              height: hp(80),
              position: "absolute",
              width: "92%",
              borderRadius: 40,
              backgroundColor: colors.surface_overlay,
              padding: 20,
              marginHorizontal: 40,
              marginBottom: 20,
              alignSelf: "center",
            },
            animatedStyle,
          ]}
        >
          <View className={`flex-row items-center justify-between`}>
            <ResponsiveUi.Text semiBold>Add 2-Factor auth</ResponsiveUi.Text>
            <X onPress={onClose} size={20} color={colors.secondary} />
          </View>
          <View className="mt-4">
            <ResponsiveUi.Text xxs regular secondary>
              Add extra layer of security with unique access codes via SMS or an
              authenticator app
            </ResponsiveUi.Text>
          </View>
          <View className="mt-6">
            <ResponsiveUi.Text xxs regular secondary>
              1. Install Google Authenticator, Authy, or any other authenticator
              app of your choice.
            </ResponsiveUi.Text>
            <ResponsiveUi.Text xxs regular secondary tailwind="mt-4">
              2. Scan the QR code below using the authenticator app.
            </ResponsiveUi.Text>
            {theme === "dark" ? (
              <QRCodeIconWhite className={`mt-5`} />
            ) : (
              <QRCodeIcon className={`mt-5`} />
            )}
            <ResponsiveUi.Text xxs regular secondary tailwind="mt-4">
              3. Enter the code generated by your authenticator app
            </ResponsiveUi.Text>
            <View className="mt-4">
              <OTPInput
                onTextChange={(text) => {
                  setOtp(text);
                  // router.navigate("/(auth)/create-password");
                }}
              />
            </View>
          </View>
          <View className="flex-1 items-end justify-end">
            <ResponsiveUi.Button
              title="Verify"
              containerStyle="mt-8"
              action={() => {}}
              disabled={otp.length < 6}
            />
          </View>
        </Animated.View>
      </BaseModal>
    </KeyboardAwareScrollView>
  );
};

export default QRCodeAuthModal;
